disabled_rules:
  - class_delegate_protocol
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - identifier_name
  - large_tuple
  - line_length
  - nesting
  - todo
  - type_body_length
  - type_name
  - weak_delegate

opt_in_rules:
  - sorted_imports

included:
  - Sources
  - Tests

excluded:

analyzer_rules:
  - unused_import

line_length: 220
#force_cast: warning
#force_try: warning