name: Publish Cocoapods

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
      - name: Lint Cocoapods
        run: pod lib lint --allow-warnings
      - name: Publish to Cocoapods registry
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push SwiftyInAppMessaging.podspec
