name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-12

    env:
      TEST: 1

    steps:
      - uses: actions/checkout@v4

      - name: Create GoogleService-Info.plist from GOOGLE_SERVICE_INFO_PLIST
        run: |
          echo GOOGLE_SERVICE_INFO_PLIST | base64 -d >> Tests/GoogleService-Info.plist
        shell: bash
        env:
          GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}

      - name: Lint
        run: |
          brew update && brew install swift-format && swift-format lint -s -r Sources -r Tests

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test